spring:
  main:
    allow-bean-definition-overriding: true

  devtools:
    add-properties: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: EMBEDDED
      schema: classpath:org/springframework/session/jdbc/schema-xxxxx.sql

server:
  port: 8080
  tomcat:
    max-connections: 8192

username: xxxxx
password: '{cipher}ass4861f4682be8131b73b56b0451a7e268c88daea3'